name: al_zikr
description: Tasbih / Zikr Counter App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  change_app_package_name: ^1.5.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_fonts: ^7.0.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  vibration: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
